# Uncomment this line to define a global platform for your project
# platform :ios, ‘7.0’

source 'https://github.com/CocoaPods/Specs.git'
workspace 'SwiftHTTP'
use_frameworks!

inhibit_all_warnings!

target 'SwiftHTTP' do
    pod 'SwiftIO', :path => '../../SwiftIO'
end
